[build]
  command = "npm run build"
  publish = "dist"

# Xem chú thích trong public/_headers về lý do chọn 'credentialless'
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "credentialless"
